
language: php

git:
    depth: 5

php:
    - 7.2
    - 7.3

install:
    - travis_retry composer clear-cache
    - travis_retry composer self-update
    - travis_retry composer install

script:
    - vendor/bin/tale-dev check --report --coverage-php-version=7.2

addons:
    code_climate:
        repo_token: b046f38e1a113e8ea7ec3e3173db1754b87b7858599f16f7f8d0f3f7a0ea6a3c
